version: "3"

networks:
  testapp-net:

#volumes:
 # testapp-db-data:

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-app
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - testapp-net
    #environment: